'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''Transact_Bad_Subscriber_Comp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Transact_Bad_Subscriber_Comp As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Panel_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Company1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''LB_CompDetails1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_CompDetails1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Search As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BT_Search1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Search1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''LB_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Company1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_CompanyName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_CompanyName1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_VID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_VID1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LB_Bulstat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Bulstat1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Bulstat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Bulstat1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_MOL_Phone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_Phone1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_MOL_Phone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_Phone1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_VAT_NUM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_VAT_NUM1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_VAT_NUM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_VAT_NUM1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_MOL_Names1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_Names1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_MOL_Names1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_Names1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_MOL_PID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_PID1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_MOL_PID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_PID1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LM_MOL_Email1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LM_MOL_Email1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_MOL_MAIL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_MAIL1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_Court_reg_City1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Court_reg_City1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Court_reg_City1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Court_reg_City1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_Segment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Segment1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LB_court_Reg_num1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_court_Reg_num1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Court_reg_num1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Court_reg_num1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_Important control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Important As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Important1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Important1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LB_Ciela_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Ciela_Company1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Ciela_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Ciela_Company1 As Global.System.Web.UI.WebControls.TextBox
End Class
