'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Reservation
    
    '''<summary>
    '''SDS_ROOM_Availa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SDS_ROOM_Availa As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LB_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Search As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DD_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_Search As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LB_Search2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Search2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TB_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Search As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BT_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Search As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BT_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_All As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BT_Navigi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Navigi As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dd_rOOM_aVAILABLE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_rOOM_aVAILABLE As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TB_Client2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Client2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_Client3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Client3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_DateOfReservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_DateOfReservation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TB_DateOfLeaving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_DateOfLeaving As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CB_Breakfast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_Breakfast As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''TCB_AllInclusive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TCB_AllInclusive As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BT_Insert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Insert As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BT_Users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Users As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BT_ROOMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_ROOMS As Global.System.Web.UI.WebControls.Button
End Class
