'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ICAP_Form

    '''<summary>
    '''TransactDecision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactDecision As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Transact_Customers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Transact_Customers As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ICAP_Company control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ICAP_Company As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Panel_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Company1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_CompDetails1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_CompDetails1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Search As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BT_Search1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Search1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LB_Company1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Company1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_CompanyName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_CompanyName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_VID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_VID1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropD_CompanyType1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropD_CompanyType1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LB_Bulstat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Bulstat1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Bulstat1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Bulstat1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_MOL_PID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_PID1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_MOL_PID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_PID1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_VAT_NUM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_VAT_NUM1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_VAT_NUM1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_VAT_NUM1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_MOL_Names1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_Names1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_MOL_Names1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_Names1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_MOL_Phone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_Phone1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_MOL_Phone1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_Phone1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_MOL_FAX1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_MOL_FAX1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_MOL_FAX1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_FAX1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LM_MOL_Email1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LM_MOL_Email1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_MOL_MAIL1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_MOL_MAIL1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Segment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Segment1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropD_Segment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropD_Segment1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LB_court_Reg_num1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_court_Reg_num1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Court_reg_num1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Court_reg_num1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Court_reg_City1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Court_reg_City1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Court_reg_City1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Court_reg_City1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Industry1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Industry1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Industry1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Industry1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_Expirian_Sole_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Expirian_Sole_2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_Comp_Det2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Comp_Det2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB_Last_Month_Paid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Last_Month_Paid2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Last_Month_Paid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Last_Month_Paid2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Num_Mont_Paid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Num_Mont_Paid2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Num_Mont_Paid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Num_Mont_Paid2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_LastYear_Turnover2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_LastYear_Turnover2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_LastYear_Turnover2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_LastYear_Turnover2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Num_Of_Empl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Num_Of_Empl2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Num_Of_empl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Num_Of_empl2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_Prevoius_Mob_History3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Prevoius_Mob_History3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB_PreviousComp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_PreviousComp3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropDPreviusMobile3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDPreviusMobile3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LB_PreviousSims3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_PreviousSims3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_PreviousSims3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_PreviousSims3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Previous_ACG_Mon_Usage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Previous_ACG_Mon_Usage3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Previous_ACG_Mon_Usage3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Previous_ACG_Mon_Usage3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_PreviousHandset3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_PreviousHandset3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBPreviousHandset3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBPreviousHandset3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_Ciela_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Ciela_4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_Ciela4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Ciela4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB_Tax_Debt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Tax_Debt4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Tax_Debt4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Tax_Debt4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_CompanyAge4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_CompanyAge4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_CompanyAge4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_CompanyAge4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Company_Reg_Date4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Company_Reg_Date4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Company_Reg_Date4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Company_Reg_Date4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Num_of_Closed4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Num_of_Closed4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Num_of_closed4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Num_of_closed4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Share_Capital4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Share_Capital4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_ShareCapital4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_ShareCapital4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_ParentComp4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_ParentComp4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DropD_ParentComp4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropD_ParentComp4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''LB_Comment4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Comment4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Comment4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Comment4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Message_Box_Comment4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Message_Box_Comment4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PanelCreditDecision5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCreditDecision5 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_CreditDecision5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_CreditDecision5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LB_Num_of_linked5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Num_of_linked5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TBNum_of_linked5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TBNum_of_linked5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Max_Credit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Max_Credit5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Max_Credit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Max_Credit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Cur_Credit_Limit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Cur_Credit_Limit5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Cur_Credit_Limit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Cur_Credit_Limit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Roaming5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Roaming5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Roaming5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Roaming5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Behavioural_Score5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Behavioural_Score5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Behavioural_Score5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Behavioural_Score5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LB_Availabale_Credit_Limit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_Availabale_Credit_Limit5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TB_Availabale_Credit_Limit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TB_Availabale_Credit_Limit5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BT_Check_TAX5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_Check_TAX5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BT_New_decision5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BT_New_decision5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_Request control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_Request As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LB_RequestForm6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LB_RequestForm6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
End Class
